# ──────────────────────────────────────────────────────────────────────────────
# windows-ssi-base.pkr.hcl
#
# Builds a pre-baked Windows Server 2025 AMI containing:
#   - Chocolatey
#   - Temurin JDK 21, .NET 8 SDK, NSSM, Git
#   - Datadog Agent MSI (downloaded, not yet configured)
# Communicator: WinRM (standard for Windows Packer builds)
# ──────────────────────────────────────────────────────────────────────────────

packer {
  required_version = ">= 1.9.0"

  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = ">= 1.3.0"
    }
  }
}

# ── Local values ──────────────────────────────────────────────────────────────
locals {
  timestamp      = formatdate("YYYYMMDD-hhmmss", timestamp())
  ami_name       = "${var.ami_name_prefix}-${local.timestamp}"
  build_date_tag = formatdate("YYYY-MM-DD", timestamp())
}

# ── Source AMI lookup: latest Windows Server 2025 Base (mirrors Terraform) ───
data "amazon-ami" "windows_2025" {
  region      = var.region
  most_recent = true
  owners      = ["amazon"]

  filters = {
    name                = "Windows_Server-2025-English-Full-Base-*"
    virtualization-type = "hvm"
  }
}

# ── Builder ───────────────────────────────────────────────────────────────────
source "amazon-ebs" "windows_ssi_base" {
  region        = var.region
  instance_type = var.instance_type

  # Use the dynamically resolved source AMI
  source_ami = data.amazon-ami.windows_2025.id

  ami_name        = local.ami_name
  ami_description = "Pre-baked Windows SSI base AMI with Java 21, .NET 8, NSSM, Git, and Datadog Agent MSI"

  # WinRM communicator — required for Windows builds
  communicator   = "winrm"
  winrm_username = "Administrator"
  winrm_use_ssl  = true
  winrm_insecure = true  # self-signed cert generated by the user_data bootstrap

  # Allow enough time for Windows to boot, run user_data, and start WinRM
  winrm_timeout = "15m"

  # Wait until the instance reaches "running" state before attempting WinRM
  pause_before_connecting = "5m"

  # User data bootstraps WinRM so Packer can connect
  # This runs once on first boot, before Packer's provisioners execute.
  user_data = <<-USERDATA
    <powershell>
    $ErrorActionPreference = "Stop"
    $ProgressPreference    = "SilentlyContinue"

    # Enable WinRM HTTPS with a self-signed certificate
    winrm quickconfig -q
    winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="1024"}'
    winrm set winrm/config '@{MaxTimeoutms="1800000"}'
    winrm set winrm/config/service '@{AllowUnencrypted="false"}'
    winrm set winrm/config/service/auth '@{Basic="true"}'

    # Create a self-signed certificate for HTTPS listener
    $cert = New-SelfSignedCertificate `
        -DnsName $env:COMPUTERNAME `
        -CertStoreLocation "cert:\LocalMachine\My"
    $thumbprint = $cert.Thumbprint

    # Remove any existing HTTPS listener and create a fresh one
    winrm delete winrm/config/listener?Address=*+Transport=HTTPS 2>$null
    winrm create winrm/config/listener?Address=*+Transport=HTTPS `
        "@{Hostname=`"$env:COMPUTERNAME`"; CertificateThumbprint=`"$thumbprint`"}"

    # Open WinRM HTTPS port in Windows Firewall
    netsh advfirewall firewall add rule `
        name="WinRM HTTPS" dir=in action=allow protocol=TCP localport=5986

    # Ensure WinRM service starts automatically
    Set-Service -Name WinRM -StartupType Automatic
    Restart-Service -Name WinRM
    </powershell>
    <persist>false</persist>
  USERDATA

  # Open WinRM HTTPS and RDP ports for Packer to reach the build instance
  temporary_security_group_source_cidrs = ["0.0.0.0/0"]

  # Root volume — Windows + all tooling needs headroom
  launch_block_device_mappings {
    device_name           = "/dev/sda1"
    volume_size           = 60
    volume_type           = "gp3"
    delete_on_termination = true
  }

  # AMI tags
  tags = {
    Name      = "windows-ssi-base-${local.timestamp}"
    SSIBase   = "true"
    BuildDate = local.build_date_tag
  }
}

# ── Build ─────────────────────────────────────────────────────────────────────
build {
  name    = "windows-ssi-base"
  sources = ["source.amazon-ebs.windows_ssi_base"]

  # ── Step 1: Install Chocolatey ─────────────────────────────────────────────
  provisioner "powershell" {
    inline = [
      "$ErrorActionPreference = 'Stop'",
      "$ProgressPreference    = 'SilentlyContinue'",
      "Write-Host '[PACKER] Installing Chocolatey...'",
      "Set-ExecutionPolicy Bypass -Scope Process -Force",
      "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072",
      "Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))",
      "$env:PATH += ';C:\\ProgramData\\chocolatey\\bin'",
      "choco --version",
      "Write-Host '[PACKER] Chocolatey installed successfully.'"
    ]
  }

  # ── Step 2: Install Java 21 (Temurin), .NET 8 SDK, NSSM, Git ──────────────
  provisioner "powershell" {
    # Chocolatey installs can be slow; allow extra time
    timeout = "30m"

    inline = [
      "$ErrorActionPreference = 'Stop'",
      "$ProgressPreference    = 'SilentlyContinue'",

      "Write-Host '[PACKER] Installing temurin21 (Java 21)...'",
      "choco install temurin21 -y --no-progress",

      "Write-Host '[PACKER] Installing dotnet-8.0-sdk...'",
      "choco install dotnet-8.0-sdk -y --no-progress",

      "Write-Host '[PACKER] Installing NSSM...'",
      "choco install nssm -y --no-progress",

      "Write-Host '[PACKER] Installing git...'",
      "choco install git -y --no-progress",

      # Refresh PATH so subsequent steps (and sysprep) inherit new binaries
      "$machinePath = [System.Environment]::GetEnvironmentVariable('PATH', 'Machine')",
      "$userPath    = [System.Environment]::GetEnvironmentVariable('PATH', 'User')",
      "$env:PATH    = $machinePath + ';' + $userPath",

      "Write-Host '[PACKER] Verifying installations...'",
      "java -version",
      "dotnet --version",
      "nssm version",
      "git --version",
      "Write-Host '[PACKER] All tools installed successfully.'"
    ]
  }

  # ── Step 3: Download Datadog Agent MSI (placeholder — no configuration) ────
  #
  # The MSI is staged to C:\Datadog so that test-time user_data can install
  # it immediately without re-downloading. API key and site are injected at
  # test time, NOT baked into the image.
  provisioner "powershell" {
    timeout = "10m"

    inline = [
      "$ErrorActionPreference = 'Stop'",
      "$ProgressPreference    = 'SilentlyContinue'",

      "Write-Host '[PACKER] Staging Datadog Agent MSI...'",
      "New-Item -ItemType Directory -Force -Path 'C:\\Datadog' | Out-Null",

      # Download the latest Datadog Agent 7 MSI for Windows x86-64
      "$ddMsiUrl  = 'https://s3.amazonaws.com/ddagent-windows-stable/datadog-agent-7-latest.amd64.msi'",
      "$ddMsiPath = 'C:\\Datadog\\datadog-agent-latest.amd64.msi'",
      "Write-Host \"[PACKER] Downloading $ddMsiUrl => $ddMsiPath\"",
      "(New-Object System.Net.WebClient).DownloadFile($ddMsiUrl, $ddMsiPath)",

      "$size = (Get-Item $ddMsiPath).Length",
      "Write-Host \"[PACKER] Datadog Agent MSI staged at $ddMsiPath ($size bytes).\"",
      "Write-Host '[PACKER] NOTE: Agent will be configured and started at test time, not here.'"
    ]
  }

  # ── Step 4: Sysprep — generalize the image ─────────────────────────────────
  #
  # Generalize removes machine-specific state (SIDs, hostname, event logs, etc.)
  # so that each EC2 instance launched from the resulting AMI gets a fresh
  # identity. Packer will create the AMI snapshot after the instance shuts down.
  provisioner "powershell" {
    inline = [
      "$ErrorActionPreference = 'Stop'",
      "Write-Host '[PACKER] Running Sysprep to generalize the image...'",

      # EC2Launch v2 ships with a built-in sysprep wrapper that correctly
      # handles AWS-specific first-boot setup (hostname, SSH keys, userdata).
      # If EC2Launch v2 is present, prefer it; otherwise fall back to the
      # classic EC2Launch path, then bare sysprep.
      "$ec2LaunchV2 = 'C:\\Program Files\\Amazon\\EC2Launch\\ec2launch.exe'",
      "$ec2LaunchV1 = 'C:\\Program Files\\Amazon\\EC2Launch\\EC2Launch.exe'",
      "$sysprepXml  = 'C:\\ProgramData\\Amazon\\EC2Launch\\sysprep\\unattend.xml'",

      "if (Test-Path $ec2LaunchV2) {",
      "    Write-Host '[PACKER] Using EC2Launch v2 sysprep...'",
      "    & $ec2LaunchV2 sysprep --shutdown",
      "} elseif (Test-Path $ec2LaunchV1) {",
      "    Write-Host '[PACKER] Using EC2Launch v1 sysprep...'",
      "    & $ec2LaunchV1 SysprepInstance",
      "} else {",
      "    Write-Host '[PACKER] Falling back to bare sysprep...'",
      "    if (Test-Path $sysprepXml) {",
      "        & C:\\Windows\\System32\\Sysprep\\sysprep.exe /oobe /generalize /shutdown /unattend:$sysprepXml",
      "    } else {",
      "        & C:\\Windows\\System32\\Sysprep\\sysprep.exe /oobe /generalize /shutdown",
      "    }",
      "}",

      "Write-Host '[PACKER] Sysprep initiated — instance will shut down.'"
    ]
  }

  # ── Post-processor: write AMI ID to packer-manifest.json ──────────────────
  post-processor "manifest" {
    output     = "packer-manifest.json"
    strip_path = true
  }
}
